name: deploy
on: [push]
jobs:
  vapor_codes:
    name: vapor.codes
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          pip3 list
          cd docs-cn
          cd 4.0
          mkdocs build
