name: deploy
on: [push]
jobs:
  deploy:
    name: cn.docs.vapor.codes
    runs-on: ubuntu-latest
    steps:
    - name: Deploying docs
      uses: appleboy/ssh-action@master
      with:
        host: vapor.codes
        username: vapor
        key: ${{ secrets.VAPOR_CODES_SSH_KEY }}
        script: ./github-actions/deploy-docs-cn.sh

