name: deploy
on: [push]
jobs:
  vapor_codes:
    name: vapor.codes
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd docs-cn
          /home/vapor/.local/bin/mkdocs build -f 4.0/mkdocs.yml -d ../build/4.0
