name: deploy
on: [push]
jobs:
  deploy:
    name: docs.vapor.codes
    runs-on: ubuntu-latest
    steps:
    - name: Deploying vapor/docs-cn
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd docs-cn
          git pull
          /home/vapor/.local/bin/mkdocs build -f 4.0/mkdocs.yml -d ../build/4.0
